version: 2
updates:
- package-ecosystem: "nuget"
  directory: "/"
  schedule:
    interval: "daily"
  groups:
    ktsu:
      patterns:
        - "ktsu.*"
    Microsoft:
      patterns:
        - "Microsoft.*"
    CommunityToolkit:
      patterns:
        - "CommunityToolkit.*"
    System:
      patterns:
        - "System.*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
